image: registry.gitlab.com/rpagyc/nbrk_currency_rates:latest
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - chmod +x ./gradlew
build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/