image: registry.gitlab.com/rpagyc/android-build-image:latest
before_script:
  - chmod +x ./gradlew
build:
  script:
    - ./gradlew helloWorld
  artifacts:
    paths:
    - nbrk_currency_rates/build/outputs/